export const DOMAINES: Record<string, string[]> = {
  developpement: ['Frontend', 'Backend', 'Full-stack', 'Mobile', 'DevOps / Cloud', 'Sécurité', 'Autre'],
  data: ['Data Science', 'Data Engineering', 'Business Intelligence', 'Machine Learning / IA', 'Autre'],
  design: ['UX / UI Design', 'Product Design', 'Design Graphique', 'Autre'],
  marketing: ['Marketing Digital', 'Growth / SEO', 'Content', 'Brand', 'Autre'],
  finance: ['Finance d\'entreprise', 'Audit / Conseil', 'Contrôle de gestion', 'Autre'],
  product: ['Product Management', 'Product Owner', 'Autre'],
  autre: ['Autre'],
}

export const DOMAINE_LABELS: Record<string, string> = {
  developpement: 'Développement',
  data: 'Data & IA',
  design: 'Design',
  marketing: 'Marketing',
  finance: 'Finance',
  product: 'Product',
  autre: 'Autre',
}

export const NIVEAUX: { value: string; label: string }[] = [
  { value: 'junior', label: 'Junior (< 5 ans)' },
  { value: 'confirme', label: 'Confirmé (5–10 ans)' },
  { value: 'senior', label: 'Senior (10–20 ans)' },
  { value: 'expert', label: 'Expert (20+ ans)' },
]

export const POSTES_PREDEFINED: string[] = [
  // === DÉVELOPPEMENT ===
  // Frontend
  'Développeur Frontend',
  'Développeur React',
  'Développeur Vue.js',
  'Développeur Angular',
  'Développeur TypeScript',
  'Développeur Web',
  'Frontend Engineer',
  'Senior Frontend Engineer',
  
  // Backend
  'Développeur Backend',
  'Développeur Node.js',
  'Développeur Python',
  'Développeur Java',
  'Développeur .NET',
  'Développeur Go',
  'Développeur Rust',
  'Backend Engineer',
  'Senior Backend Engineer',
  'Architect Backend',
  
  // Full-Stack
  'Développeur Full-Stack',
  'Full-Stack Engineer',
  'Full-Stack Developer',
  'Développeur MEAN',
  'Développeur MERN',
  'Développeur Fullstack JavaScript',
  
  // Mobile
  'Développeur Mobile',
  'Développeur iOS',
  'Développeur Android',
  'Développeur Flutter',
  'Développeur React Native',
  'Mobile Engineer',
  'Mobile Developer',
  'Senior Mobile Developer',
  
  // DevOps / Cloud / Infrastructure
  'DevOps Engineer',
  'Ingénieur DevOps',
  'Ingénieur Cloud',
  'Ingénieur Cloud AWS',
  'Ingénieur Cloud Azure',
  'Ingénieur Cloud GCP',
  'Ingénieur Kubernetes',
  'Ingénieur Docker',
  'SRE (Site Reliability Engineer)',
  'Infrastructure Engineer',
  'Platform Engineer',
  'Cloud Architect',
  
  // Sécurité
  'Ingénieur Sécurité',
  'Security Engineer',
  'DevSecOps Engineer',
  'Pentesteur',
  'Responsable Sécurité Informatique',
  'CISO (Chief Information Security Officer)',
  'Analyste Sécurité',
  'Expert en Cybersécurité',
  
  // Autre développement
  'Développeur ERP',
  'Développeur CRM',
  'Développeur Web Services',
  'Développeur API',
  'Développeur Database',
  'CTO (Chief Technology Officer)',
  'Technical Lead',
  'Architect',
  'Software Architect',
  'Lead Developer',
  'Tech Lead',
  
  // === DATA & IA ===
  'Data Scientist',
  'Senior Data Scientist',
  'Lead Data Scientist',
  'Data Engineer',
  'Senior Data Engineer',
  'Data Analyst',
  'Senior Data Analyst',
  'Analytics Engineer',
  'Business Analyst',
  'Data Manager',
  'Machine Learning Engineer',
  'Senior Machine Learning Engineer',
  'ML Ops Engineer',
  'Data Architect',
  'BI Engineer',
  'Business Intelligence Developer',
  'BI Architect',
  'Analytics Manager',
  'Chief Data Officer (CDO)',
  'AI Engineer',
  'AI Specialist',
  'LLM Engineer',
  'NLP Engineer',
  'Computer Vision Engineer',
  
  // === DESIGN ===
  'UX Designer',
  'Senior UX Designer',
  'Lead UX Designer',
  'UI Designer',
  'Senior UI Designer',
  'UX/UI Designer',
  'Product Designer',
  'Senior Product Designer',
  'Design Graphique',
  'Graphic Designer',
  'Web Designer',
  'Interaction Designer',
  'User Research',
  'Research Lead',
  'Design Système Architect',
  'Design Director',
  'Creative Director',
  'Design Manager',
  
  // === MARKETING ===
  'Responsable Marketing Digital',
  'Marketing Manager',
  'Digital Marketing Manager',
  'Growth Manager',
  'Growth Hacker',
  'Growth Lead',
  'SEO Specialist',
  'SEO Manager',
  'SEM Manager',
  'Content Manager',
  'Content Strategist',
  'Community Manager',
  'Social Media Manager',
  'Email Marketing Specialist',
  'Brand Manager',
  'Brand Strategist',
  'Product Marketer',
  'Marketing Analyst',
  'Copywriter',
  'Content Writer',
  'CMO (Chief Marketing Officer)',
  'Demand Gen Manager',
  'Lead Generation Specialist',
  'Marketing Automation Specialist',
  
  // === PRODUCT ===
  'Product Manager',
  'Senior Product Manager',
  'Lead Product Manager',
  'Product Owner',
  'Senior Product Owner',
  'Associate Product Manager',
  'APM (Associate Product Manager)',
  'Director of Product',
  'VP Product',
  'Chief Product Officer (CPO)',
  'Product Strategy Manager',
  'Product Marketing Manager',
  'Product Analyst',
  
  // === GESTION DE PROJET ===
  'Chef de projet',
  'Chef de projet digital',
  'Chef de projet technique',
  'Chef de projet agile',
  'Scrum Master',
  'Agile Coach',
  'Project Manager',
  'Technical Project Manager',
  'Program Manager',
  'Director of Programs',
  'PMO Manager',
  'Product & Project Manager',
  
  // === FINANCE ===
  'Analyste financier',
  'Senior Analyste financier',
  'Contrôleur de gestion',
  'Senior Contrôleur de gestion',
  'Auditeur interne',
  'Auditeur externe',
  'Consultant IT',
  'Consultant technique',
  'Management Consultant',
  'Stratégie Consultant',
  'Finance Manager',
  'Finance Controller',
  'CFO (Chief Financial Officer)',
  'Trésorier',
  'Responsable Comptabilité',
  
  // === RH / OPÉRATIONS ===
  'Responsable RH',
  'Gestionnaire RH',
  'Recruteur',
  'Tech Recruiter',
  'HR Manager',
  'Chief People Officer',
  'Operations Manager',
  'Responsable Opérations',
  
  // === VENTES / BUSINESS ===
  'Business Development Manager',
  'Sales Manager',
  'Account Executive',
  'Sales Representative',
  'Key Account Manager',
  'Solutions Engineer',
  'Solutions Architect',
  'Solution Consultant',
  'Enterprise Account Manager',
  'VP Sales',
  'Chief Revenue Officer (CRO)',
  
  // === AUTRE ===
  'Consultant',
  'Freelancer',
  'Manager',
  'Lead',
  'Developer',
]